import = ["~/.config/alacritty/themes/vague.toml"]

general.live_config_reload = true

[font]
size = 9

[font.glyph_offset]
x = 0
y = 1

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mode = "~Vi"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
#mods = "Command" # macos
mods = "Control"  # linux

#for macos
#[[keyboard.bindings]]
#action = "Paste"
#key = "V"
#mods = "Command" # macos

#for macos
#[[keyboard.bindings]]
#action = "Copy"
#key = "C"
#mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "Hide"
key = "H"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "Minimize"
key = "M"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "Quit"
key = "Q"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
#mods = "Command|Control" # macos
mods = "Control"          # linux

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
#mods = "Command" # macos
mods = "Control"  # linux

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
#mods = "Command" # macos
mods = "Control"  # linux

[mouse]
hide_when_typing = true

[terminal.shell]
args = ["-l", "-c", "tmux new -As alacritty"]
program = "/bin/zsh"

[window]
opacity = 0.95
